# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"
  version "1.15.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfswitch"
  bash_completion "tfswitch-completion.bash"
  fish_completion "tfswitch-completion.fish"

  on_linux do
    on_intel do
      url "https://github.com/yermulnik/tfswitch/releases/download/v#{version}/tfswitch_v#{version}_linux_amd64.tar.gz"
      sha256 "67b79a12fb56f361d51095e77d7b976c5e85fd2d5fd310d865623e1ad307afa0"
    end
  end

  conflicts_with cask: [
      "terraform",
    ]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfswitch"]
    end
  end

  caveats do
    "Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown"
  end

  # No zap stanza required
end
