# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfswitch"
  bash_completion "tfswitch-completion.bash"
  fish_completion "tfswitch-completion.fish"

  on_linux do
    on_intel do
      url "https://github.com/yermulnik/tfswitch/releases/download/v#{version}/tfswitch_v#{version}_linux_amd64.tar.gz"
      sha256 "bff956d6e981a452245ef08c406d5acc37829b2130a88c732b0619a5abdbcd33"
    end
  end

  conflicts_with cask: [
      "terraform",
      "tfswitch",
    ]

  caveats do
    "Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown"
  end

  # No zap stanza required
end
