# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfswitch" do
  name "tfswitch"
  desc "The tfswitch command lets you switch between terraform versions."
  homepage "https://warrensbox.github.io/terraform-switcher"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfswitch"
  bash_completion "tfswitch-completion.bash"
  fish_completion "tfswitch-completion.fish"

  on_linux do
    on_intel do
      url "https://github.com/yermulnik/tfswitch/releases/download/v#{version}/tfswitch_v0.0.0_linux_amd64.tar.gz"
      sha256 "00ace26e778549a4a22a986a8289460f4f43cf9e7fd3b3d5ffc462c7999d002e"
    end
  end

  conflicts_with cask: [
      "terraform",
    ]

  caveats do
    "Type 'tfswitch' on your command line and choose Terraform version that you want from the dropdown"
  end

  # No zap stanza required
end
